spring.application.name=dev
spring.datasource.url=jdbc:postgresql://localhost:8000/stardepiller
spring.datasource.username=stardepiller
spring.datasource.password=159753
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.port=8081